// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXXU-q_EKX-veum2HnEIoldOwd8sH4IWA',
    appId: '1:354140735102:web:565afa4c6f94b129167a2f',
    messagingSenderId: '354140735102',
    projectId: 'flutter-reddit-clone-41db7',
    authDomain: 'flutter-reddit-clone-41db7.firebaseapp.com',
    storageBucket: 'flutter-reddit-clone-41db7.firebasestorage.app',
    measurementId: 'G-RG8TMSNNZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyCNisD7P_-wXIcKFpVLjB6HKUVmj8Fw4',
    appId: '1:354140735102:android:110a25c61be0542b167a2f',
    messagingSenderId: '354140735102',
    projectId: 'flutter-reddit-clone-41db7',
    storageBucket: 'flutter-reddit-clone-41db7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD140Ehbk8DTVjo36Ds3U5Ngu8TjYrQTQs',
    appId: '1:354140735102:ios:e88de076c0849d9a167a2f',
    messagingSenderId: '354140735102',
    projectId: 'flutter-reddit-clone-41db7',
    storageBucket: 'flutter-reddit-clone-41db7.firebasestorage.app',
    androidClientId: '354140735102-kecu5nmg2f7scelgbdm80sdqiheo2o89.apps.googleusercontent.com',
    iosClientId: '354140735102-0qfvin6dlbg70k1c50gn9bskumb6kj9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
